# Generated by Django 3.1.6 on 2022-01-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20201212_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersprofile',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/upload/members'),
        ),
    ]
