# Generated by Django 3.1.6 on 2022-01-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20220105_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membersprofile',
            old_name='img',
            new_name='photo',
        ),
    ]
