# Generated by Django 3.1.6 on 2022-01-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20220106_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name of the community')),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='static/img/upload/community')),
            ],
            options={
                'verbose_name_plural': 'Community Profiles',
                'ordering': ['-id'],
            },
        ),
    ]
